### ISSUE TITLE
Macht das Sinn?

### ISSUE THREAD

**Issue by geometric-design** [rwgaj/gittest#1]
https://github.com/rwgaj/gittest/blob/3e8a9960a1dc5ff74812330bcdc680d15ea480ab/.gitignore#L8

War das nur zur Übung oder macht es Sinn die .gitignore mit auf das repo zu pushen? Die ignorierten Dateien werden ja sowieso nicht hochgeladen, deshalb benötigen andere das doch auch nicht um "den selben kram" bei sich zu ignorieren... Oder wurde dir diesbezüglich etwas beigebracht im Geschäft? Wenn ja: Was/Wieso/Warum?

**Comment by rwgaj** [comment]
Ne hab ich einfach so gemacht, hatte keinen speziellen Grund ^^
